"""
data_round4.py — JobRole 직무 데이터

포함 내용:
  JOB_ROLES        : 15개 직무 노드 (iri, name, category, keywords)
  COURSE_JOB_FITS  : 과목-직무 적합도 엣지 (courseCode, jobIri, weight 0~1)
  TARGETS_JOB_ROLE : 전공-직무 연결 (majorIri, jobIri) — 기존 스키마 활용

확장 계획: 취업지원팀 DB 연동 시 과목별 fit 통계로 weight 자동 보정
"""

# ── JobRole 노드 ───────────────────────────────────────────────────
JOB_ROLES = [
    {
        "iri":      "Job_무역영업",
        "name":     "무역·해외영업",
        "category": "비즈니스",
        "keywords": "무역,수출입,해외영업,협상,중국어,영어,바이어,인코텀즈,물류,통관,FTA",
    },
    {
        "iri":      "Job_컨설팅",
        "name":     "경영컨설팅·전략",
        "category": "비즈니스",
        "keywords": "컨설팅,전략,분석,문제해결,프레임워크,리서치,벤치마킹,제안,사업성,M&A",
    },
    {
        "iri":      "Job_데이터분석",
        "name":     "데이터분석·BI",
        "category": "테크",
        "keywords": "데이터분석,통계,SQL,Python,R,시각화,대시보드,BI,머신러닝,회귀,예측",
    },
    {
        "iri":      "Job_소프트웨어",
        "name":     "소프트웨어개발",
        "category": "테크",
        "keywords": "백엔드,프론트엔드,개발,Java,Python,JavaScript,API,데이터베이스,클라우드,DevOps",
    },
    {
        "iri":      "Job_AI엔지니어",
        "name":     "AI·ML 엔지니어",
        "category": "테크",
        "keywords": "인공지능,머신러닝,딥러닝,PyTorch,TensorFlow,NLP,컴퓨터비전,모델,파인튜닝,LLM",
    },
    {
        "iri":      "Job_마케팅",
        "name":     "마케팅·브랜드",
        "category": "비즈니스",
        "keywords": "마케팅,브랜드,디지털마케팅,SNS,콘텐츠,광고,시장조사,소비자행동,퍼포먼스,CRM",
    },
    {
        "iri":      "Job_금융",
        "name":     "금융·투자",
        "category": "금융",
        "keywords": "금융,투자,자산운용,파생상품,채권,주식,IB,벨류에이션,리스크,포트폴리오,재무",
    },
    {
        "iri":      "Job_기획",
        "name":     "경영·서비스 기획",
        "category": "비즈니스",
        "keywords": "기획,사업기획,서비스기획,전략,프로세스,KPI,로드맵,보고서,조직관리,운영",
    },
    {
        "iri":      "Job_인사",
        "name":     "인사·HR",
        "category": "비즈니스",
        "keywords": "인사,HR,채용,조직관리,노사관계,평가,보상,역량개발,교육훈련,HRBP",
    },
    {
        "iri":      "Job_PR언론",
        "name":     "PR·홍보·언론",
        "category": "미디어",
        "keywords": "PR,홍보,미디어,언론,보도자료,스피치,위기관리,커뮤니케이션,기자,방송",
    },
    {
        "iri":      "Job_교육",
        "name":     "교육·콘텐츠",
        "category": "교육",
        "keywords": "교육,교직,강의,커리큘럼,콘텐츠개발,이러닝,에듀테크,학습설계,코칭",
    },
    {
        "iri":      "Job_국제기구",
        "name":     "국제기구·외교",
        "category": "공공",
        "keywords": "국제기구,외교,글로벌정책,UN,ODA,국제협력,다자외교,외교부,KOICA,국제법",
    },
    {
        "iri":      "Job_반도체",
        "name":     "반도체·회로설계",
        "category": "테크",
        "keywords": "반도체,회로설계,VLSI,공정,팹,테스트,FPGA,임베디드,RF,아날로그,디지털",
    },
    {
        "iri":      "Job_PM",
        "name":     "프로덕트 매니저",
        "category": "테크",
        "keywords": "PM,PO,프로덕트,기획,UX,사용자인터뷰,스프린트,애자일,로드맵,A/B테스트",
    },
    {
        "iri":      "Job_회계세무",
        "name":     "회계·세무·감사",
        "category": "금융",
        "keywords": "회계,세무,감사,재무제표,IFRS,원가회계,세법,공인회계사,CPA,내부통제",
    },
]

# ── 과목-직무 적합도 엣지 ─────────────────────────────────────────
# weight: 0.0~1.0 (높을수록 해당 직무에 핵심 과목)
COURSE_JOB_FITS: list[dict] = [

    # ── 중문학과 (Dept_CHI) ──────────────────────────────────────
    {"courseCode": "CHI4008", "jobIri": "Job_무역영업",  "weight": 0.95},
    {"courseCode": "CHI4008", "jobIri": "Job_국제기구",  "weight": 0.65},
    {"courseCode": "CHI4014", "jobIri": "Job_무역영업",  "weight": 0.80},
    {"courseCode": "CHI4014", "jobIri": "Job_국제기구",  "weight": 0.75},
    {"courseCode": "CHI4014", "jobIri": "Job_컨설팅",    "weight": 0.60},
    {"courseCode": "CHI4015", "jobIri": "Job_무역영업",  "weight": 0.85},
    {"courseCode": "CHI4015", "jobIri": "Job_컨설팅",    "weight": 0.70},
    {"courseCode": "CHI3039", "jobIri": "Job_무역영업",  "weight": 0.80},
    {"courseCode": "CHI3039", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "CHI3037", "jobIri": "Job_무역영업",  "weight": 0.75},
    {"courseCode": "CHI3037", "jobIri": "Job_국제기구",  "weight": 0.65},
    {"courseCode": "CHI3036", "jobIri": "Job_국제기구",  "weight": 0.75},
    {"courseCode": "CHI3036", "jobIri": "Job_PR언론",    "weight": 0.60},
    {"courseCode": "CHI4007", "jobIri": "Job_무역영업",  "weight": 0.80},
    {"courseCode": "CHI4007", "jobIri": "Job_국제기구",  "weight": 0.70},
    {"courseCode": "CHI4013", "jobIri": "Job_무역영업",  "weight": 0.70},
    {"courseCode": "CHI3024", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "CHI3024", "jobIri": "Job_PR언론",    "weight": 0.60},

    # ── 경영학과 (Dept_MGT) ──────────────────────────────────────
    {"courseCode": "MGT3006", "jobIri": "Job_마케팅",    "weight": 0.95},
    {"courseCode": "MGT3006", "jobIri": "Job_기획",      "weight": 0.70},
    {"courseCode": "MGT3004", "jobIri": "Job_금융",      "weight": 0.90},
    {"courseCode": "MGT3004", "jobIri": "Job_회계세무",  "weight": 0.75},
    {"courseCode": "MGT4102", "jobIri": "Job_컨설팅",    "weight": 0.90},
    {"courseCode": "MGT4102", "jobIri": "Job_기획",      "weight": 0.85},
    {"courseCode": "MGT4106", "jobIri": "Job_인사",      "weight": 0.95},
    {"courseCode": "MGT4107", "jobIri": "Job_인사",      "weight": 0.85},
    {"courseCode": "MGT3002", "jobIri": "Job_PM",        "weight": 0.80},
    {"courseCode": "MGT3002", "jobIri": "Job_기획",      "weight": 0.75},
    {"courseCode": "MGT3007", "jobIri": "Job_무역영업",  "weight": 0.80},
    {"courseCode": "MGT3007", "jobIri": "Job_컨설팅",    "weight": 0.75},
    {"courseCode": "MGT4207", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "MGT4207", "jobIri": "Job_AI엔지니어","weight": 0.80},
    {"courseCode": "MGT4202", "jobIri": "Job_데이터분석","weight": 0.90},
    {"courseCode": "MGT4202", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "MGT3005", "jobIri": "Job_회계세무",  "weight": 0.90},
    {"courseCode": "MGT3005", "jobIri": "Job_컨설팅",    "weight": 0.70},
    {"courseCode": "MGT2003", "jobIri": "Job_회계세무",  "weight": 0.95},
    {"courseCode": "MGT2003", "jobIri": "Job_금융",      "weight": 0.70},
    {"courseCode": "MGT4104", "jobIri": "Job_인사",      "weight": 0.80},
    {"courseCode": "MGT4104", "jobIri": "Job_기획",      "weight": 0.65},
    {"courseCode": "MGT4201", "jobIri": "Job_컨설팅",    "weight": 0.75},
    {"courseCode": "MGT4201", "jobIri": "Job_기획",      "weight": 0.70},
    {"courseCode": "MGT4208", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "MGT4208", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "MGT4221", "jobIri": "Job_PM",        "weight": 0.75},
    {"courseCode": "MGT4221", "jobIri": "Job_소프트웨어","weight": 0.60},
    {"courseCode": "MGT4103", "jobIri": "Job_컨설팅",    "weight": 0.80},
    {"courseCode": "MGT4103", "jobIri": "Job_기획",      "weight": 0.75},
    {"courseCode": "MGT2002", "jobIri": "Job_데이터분석","weight": 0.75},
    {"courseCode": "MGT2002", "jobIri": "Job_금융",      "weight": 0.70},

    # ── 경제학과 (Dept_ECO) ──────────────────────────────────────
    {"courseCode": "ECO3008", "jobIri": "Job_금융",      "weight": 0.90},
    {"courseCode": "ECO3008", "jobIri": "Job_데이터분석","weight": 0.70},
    {"courseCode": "ECO4009", "jobIri": "Job_금융",      "weight": 0.95},
    {"courseCode": "ECO4025", "jobIri": "Job_금융",      "weight": 0.90},
    {"courseCode": "ECO4025", "jobIri": "Job_컨설팅",    "weight": 0.75},
    {"courseCode": "ECO3010", "jobIri": "Job_무역영업",  "weight": 0.85},
    {"courseCode": "ECO3010", "jobIri": "Job_국제기구",  "weight": 0.75},
    {"courseCode": "ECO2009", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "ECO2009", "jobIri": "Job_금융",      "weight": 0.80},
    {"courseCode": "ECO4004", "jobIri": "Job_데이터분석","weight": 0.90},
    {"courseCode": "ECO3023", "jobIri": "Job_AI엔지니어","weight": 0.80},
    {"courseCode": "ECO3023", "jobIri": "Job_금융",      "weight": 0.85},
    {"courseCode": "ECO3023", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "ECO4032", "jobIri": "Job_금융",      "weight": 0.85},
    {"courseCode": "ECO4032", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "ECO3011", "jobIri": "Job_금융",      "weight": 0.85},
    {"courseCode": "ECO3011", "jobIri": "Job_국제기구",  "weight": 0.70},
    {"courseCode": "ECO4008", "jobIri": "Job_금융",      "weight": 0.85},
    {"courseCode": "ECO4008", "jobIri": "Job_국제기구",  "weight": 0.65},
    {"courseCode": "ECO4010", "jobIri": "Job_금융",      "weight": 0.85},
    {"courseCode": "ECO2004", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "ECO4005", "jobIri": "Job_컨설팅",    "weight": 0.75},
    {"courseCode": "ECO4005", "jobIri": "Job_금융",      "weight": 0.70},

    # ── 컴퓨터공학과 (Dept_CSE) ──────────────────────────────────
    {"courseCode": "CSE3080", "jobIri": "Job_소프트웨어","weight": 0.95},
    {"courseCode": "CSE3080", "jobIri": "Job_AI엔지니어","weight": 0.85},
    {"courseCode": "CSE3081", "jobIri": "Job_소프트웨어","weight": 0.95},
    {"courseCode": "CSE3081", "jobIri": "Job_AI엔지니어","weight": 0.85},
    {"courseCode": "CSE4185", "jobIri": "Job_AI엔지니어","weight": 0.95},
    {"courseCode": "CSE4185", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "CSE4130", "jobIri": "Job_AI엔지니어","weight": 0.95},
    {"courseCode": "CSE4130", "jobIri": "Job_데이터분석","weight": 0.90},
    {"courseCode": "CSE4110", "jobIri": "Job_소프트웨어","weight": 0.90},
    {"courseCode": "CSE4110", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "CSE4115", "jobIri": "Job_소프트웨어","weight": 0.90},
    {"courseCode": "CSE4115", "jobIri": "Job_PM",        "weight": 0.75},
    {"courseCode": "CSE4070", "jobIri": "Job_소프트웨어","weight": 0.90},
    {"courseCode": "CSE4070", "jobIri": "Job_반도체",    "weight": 0.65},
    {"courseCode": "CSE4175", "jobIri": "Job_소프트웨어","weight": 0.85},
    {"courseCode": "CSE4175", "jobIri": "Job_반도체",    "weight": 0.60},
    {"courseCode": "CSE4170", "jobIri": "Job_소프트웨어","weight": 0.75},
    {"courseCode": "CSE4170", "jobIri": "Job_PM",        "weight": 0.60},
    {"courseCode": "CSE2003", "jobIri": "Job_소프트웨어","weight": 0.80},
    {"courseCode": "CSE2003", "jobIri": "Job_데이터분석","weight": 0.70},
    {"courseCode": "CSE4100", "jobIri": "Job_소프트웨어","weight": 0.85},
    {"courseCode": "CSE4100", "jobIri": "Job_반도체",    "weight": 0.65},
    {"courseCode": "CSE4188", "jobIri": "Job_소프트웨어","weight": 0.75},
    {"courseCode": "CSE3013", "jobIri": "Job_소프트웨어","weight": 0.80},
    {"courseCode": "CSE4050", "jobIri": "Job_소프트웨어","weight": 0.85},
    {"courseCode": "CSE4010", "jobIri": "Job_소프트웨어","weight": 0.85},
    {"courseCode": "CSE4010", "jobIri": "Job_반도체",    "weight": 0.70},

    # ── 전자공학과 (Dept_EEE) ────────────────────────────────────
    {"courseCode": "EEE3146", "jobIri": "Job_반도체",    "weight": 0.95},
    {"courseCode": "EEE3202", "jobIri": "Job_반도체",    "weight": 0.95},
    {"courseCode": "EEE4203", "jobIri": "Job_반도체",    "weight": 0.90},
    {"courseCode": "EEE3163", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "EEE3163", "jobIri": "Job_소프트웨어","weight": 0.65},
    {"courseCode": "EEE3142", "jobIri": "Job_AI엔지니어","weight": 0.85},
    {"courseCode": "EEE3142", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "EEE3148", "jobIri": "Job_반도체",    "weight": 0.75},
    {"courseCode": "EEE3148", "jobIri": "Job_소프트웨어","weight": 0.60},
    {"courseCode": "EEE3121", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "EEE3131", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "EEE3132", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "EEE2135", "jobIri": "Job_반도체",    "weight": 0.80},
    {"courseCode": "EEE2135", "jobIri": "Job_소프트웨어","weight": 0.65},
    {"courseCode": "EEE3178", "jobIri": "Job_반도체",    "weight": 0.75},
    {"courseCode": "EEE3178", "jobIri": "Job_소프트웨어","weight": 0.70},
    {"courseCode": "EEE2108", "jobIri": "Job_소프트웨어","weight": 0.80},
    {"courseCode": "EEE2108", "jobIri": "Job_AI엔지니어","weight": 0.75},

    # ── 국어국문학과 (Dept_KOR) ──────────────────────────────────────
    {"courseCode": "KOR3011", "jobIri": "Job_AI엔지니어","weight": 0.55},
    {"courseCode": "KOR3012", "jobIri": "Job_PR언론",    "weight": 0.70},
    {"courseCode": "KOR3012", "jobIri": "Job_교육",      "weight": 0.65},
    {"courseCode": "KOR3205", "jobIri": "Job_PR언론",    "weight": 0.80},
    {"courseCode": "KOR3205", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "KOR3207", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "KOR3211", "jobIri": "Job_PR언론",    "weight": 0.65},
    {"courseCode": "KOR3211", "jobIri": "Job_교육",      "weight": 0.65},
    {"courseCode": "KOR3213", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "KOR3213", "jobIri": "Job_기획",      "weight": 0.60},

    # ── 영어영문학과 (Dept_ENG) ──────────────────────────────────────
    {"courseCode": "ENG3404", "jobIri": "Job_무역영업",  "weight": 0.75},
    {"courseCode": "ENG3404", "jobIri": "Job_국제기구",  "weight": 0.70},
    {"courseCode": "ENG3405", "jobIri": "Job_교육",      "weight": 0.85},
    {"courseCode": "ENG3301", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "ENG3302", "jobIri": "Job_교육",      "weight": 0.65},
    {"courseCode": "ENG3302", "jobIri": "Job_AI엔지니어","weight": 0.55},

    # ── 유럽문화학과 (Dept_EUR) ──────────────────────────────────────
    {"courseCode": "EUR3101", "jobIri": "Job_국제기구",  "weight": 0.90},
    {"courseCode": "EUR3101", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "EUR3101", "jobIri": "Job_PR언론",    "weight": 0.60},
    {"courseCode": "EUR3102", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "EUR3102", "jobIri": "Job_국제기구",  "weight": 0.65},

    # ── 미국문화학과 (Dept_AMC) ──────────────────────────────────────
    {"courseCode": "AMC3014", "jobIri": "Job_무역영업",  "weight": 0.65},
    {"courseCode": "AMC3014", "jobIri": "Job_국제기구",  "weight": 0.60},
    {"courseCode": "AMC3070", "jobIri": "Job_PR언론",    "weight": 0.65},
    {"courseCode": "AMC3070", "jobIri": "Job_국제기구",  "weight": 0.65},
    {"courseCode": "AMC4120", "jobIri": "Job_국제기구",  "weight": 0.75},
    {"courseCode": "AMC4120", "jobIri": "Job_컨설팅",    "weight": 0.65},

    # ── 사학과 (Dept_HIS) ────────────────────────────────────────────
    {"courseCode": "HIS2002", "jobIri": "Job_교육",      "weight": 0.75},
    {"courseCode": "HIS2002", "jobIri": "Job_국제기구",  "weight": 0.65},
    {"courseCode": "HIS3060", "jobIri": "Job_국제기구",  "weight": 0.85},
    {"courseCode": "HIS3060", "jobIri": "Job_컨설팅",    "weight": 0.60},
    {"courseCode": "HIS3038", "jobIri": "Job_국제기구",  "weight": 0.70},
    {"courseCode": "HIS3038", "jobIri": "Job_교육",      "weight": 0.70},

    # ── 철학과 (Dept_PHI) ────────────────────────────────────────────
    {"courseCode": "PHI3001", "jobIri": "Job_교육",      "weight": 0.75},
    {"courseCode": "PHI3025", "jobIri": "Job_PR언론",    "weight": 0.65},
    {"courseCode": "PHI3025", "jobIri": "Job_교육",      "weight": 0.65},
    {"courseCode": "PHI4009", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "PHI4009", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "PHI4009", "jobIri": "Job_인사",      "weight": 0.60},
    {"courseCode": "PHI4040", "jobIri": "Job_AI엔지니어","weight": 0.60},
    {"courseCode": "PHI4040", "jobIri": "Job_데이터분석","weight": 0.55},

    # ── 사회학과 (Dept_SOC) ──────────────────────────────────────────
    {"courseCode": "SOC3001", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "SOC3001", "jobIri": "Job_PR언론",    "weight": 0.65},
    {"courseCode": "SOC3007", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "SOC3007", "jobIri": "Job_인사",      "weight": 0.60},
    {"courseCode": "SOC3019", "jobIri": "Job_교육",      "weight": 0.80},
    {"courseCode": "SOC3022", "jobIri": "Job_컨설팅",    "weight": 0.70},
    {"courseCode": "SOC3022", "jobIri": "Job_금융",      "weight": 0.55},
    {"courseCode": "SOC3033", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "SOC3033", "jobIri": "Job_PR언론",    "weight": 0.60},

    # ── 정치외교학과 (Dept_POL) ──────────────────────────────────────
    {"courseCode": "POL3130", "jobIri": "Job_국제기구",  "weight": 0.90},
    {"courseCode": "POL3130", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "POL3097", "jobIri": "Job_데이터분석","weight": 0.70},
    {"courseCode": "POL3097", "jobIri": "Job_컨설팅",    "weight": 0.65},
    {"courseCode": "POL4095", "jobIri": "Job_데이터분석","weight": 0.75},
    {"courseCode": "POL4095", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "POL4095", "jobIri": "Job_PR언론",    "weight": 0.70},
    {"courseCode": "POL3090", "jobIri": "Job_국제기구",  "weight": 0.75},
    {"courseCode": "POL3090", "jobIri": "Job_컨설팅",    "weight": 0.60},

    # ── 심리학과 (Dept_PSY) ──────────────────────────────────────────
    {"courseCode": "PSY3008", "jobIri": "Job_인사",      "weight": 0.75},
    {"courseCode": "PSY3008", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "PSY3018", "jobIri": "Job_교육",      "weight": 0.80},
    {"courseCode": "PSY3019", "jobIri": "Job_인사",      "weight": 0.75},
    {"courseCode": "PSY3019", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "PSY4032", "jobIri": "Job_인사",      "weight": 0.80},
    {"courseCode": "PSY4009", "jobIri": "Job_PM",        "weight": 0.70},
    {"courseCode": "PSY4009", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "PSY4009", "jobIri": "Job_인사",      "weight": 0.65},

    # ── 수학과 (Dept_MAT) ────────────────────────────────────────────
    {"courseCode": "MAT3420", "jobIri": "Job_금융",      "weight": 0.95},
    {"courseCode": "MAT3420", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "MAT3410", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "MAT3410", "jobIri": "Job_AI엔지니어","weight": 0.80},
    {"courseCode": "MAT3410", "jobIri": "Job_금융",      "weight": 0.75},
    {"courseCode": "MAT2420", "jobIri": "Job_데이터분석","weight": 0.70},
    {"courseCode": "MAT2420", "jobIri": "Job_AI엔지니어","weight": 0.65},
    {"courseCode": "MAT3440", "jobIri": "Job_AI엔지니어","weight": 0.70},
    {"courseCode": "MAT3440", "jobIri": "Job_소프트웨어","weight": 0.60},
    {"courseCode": "MAT3450", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "MAT3450", "jobIri": "Job_AI엔지니어","weight": 0.75},
    {"courseCode": "MAT3450", "jobIri": "Job_소프트웨어","weight": 0.65},

    # ── 생명과학과 (Dept_BIO) ────────────────────────────────────────
    {"courseCode": "BIO3212", "jobIri": "Job_데이터분석","weight": 0.60},
    {"courseCode": "BIO3212", "jobIri": "Job_기획",      "weight": 0.55},
    {"courseCode": "BIO4203", "jobIri": "Job_컨설팅",    "weight": 0.70},
    {"courseCode": "BIO4203", "jobIri": "Job_기획",      "weight": 0.65},
    {"courseCode": "BIO2511", "jobIri": "Job_데이터분석","weight": 0.55},
    {"courseCode": "BIO2701", "jobIri": "Job_국제기구",  "weight": 0.60},
    {"courseCode": "BIO2701", "jobIri": "Job_컨설팅",    "weight": 0.55},

    # ── 신문방송·광고학과 (Dept_JAS) ────────────────────────────────
    {"courseCode": "JAS3001", "jobIri": "Job_PR언론",    "weight": 0.95},
    {"courseCode": "JAS3001", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "JAS3002", "jobIri": "Job_PR언론",    "weight": 0.90},
    {"courseCode": "JAS3002", "jobIri": "Job_국제기구",  "weight": 0.60},
    {"courseCode": "JAS3003", "jobIri": "Job_PR언론",    "weight": 0.75},
    {"courseCode": "JAS3003", "jobIri": "Job_데이터분석","weight": 0.60},
    {"courseCode": "JAS3007", "jobIri": "Job_마케팅",    "weight": 0.90},
    {"courseCode": "JAS3007", "jobIri": "Job_PR언론",    "weight": 0.75},
    {"courseCode": "JAS3007", "jobIri": "Job_기획",      "weight": 0.70},
    {"courseCode": "JAS3015", "jobIri": "Job_마케팅",    "weight": 0.85},
    {"courseCode": "JAS3015", "jobIri": "Job_기획",      "weight": 0.70},
    {"courseCode": "JAS4012", "jobIri": "Job_기획",      "weight": 0.80},
    {"courseCode": "JAS4012", "jobIri": "Job_PM",        "weight": 0.75},
    {"courseCode": "JAS4012", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "JAS4016", "jobIri": "Job_마케팅",    "weight": 0.90},
    {"courseCode": "JAS4016", "jobIri": "Job_PR언론",    "weight": 0.75},

    # ── 미디어·아트·엔터테인먼트 (Dept_MAE) ─────────────────────────
    {"courseCode": "MAE3001", "jobIri": "Job_PR언론",    "weight": 0.85},
    {"courseCode": "MAE3001", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "MAE3002", "jobIri": "Job_PR언론",    "weight": 0.75},
    {"courseCode": "MAE3002", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "MAE3009", "jobIri": "Job_기획",      "weight": 0.80},
    {"courseCode": "MAE3009", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "MAE3009", "jobIri": "Job_PM",        "weight": 0.65},
    {"courseCode": "MAE4004", "jobIri": "Job_PR언론",    "weight": 0.80},
    {"courseCode": "MAE4004", "jobIri": "Job_마케팅",    "weight": 0.70},
    {"courseCode": "MAE4016", "jobIri": "Job_PM",        "weight": 0.80},
    {"courseCode": "MAE4016", "jobIri": "Job_기획",      "weight": 0.80},
    {"courseCode": "MAE4016", "jobIri": "Job_마케팅",    "weight": 0.65},
    {"courseCode": "MAE4025", "jobIri": "Job_기획",      "weight": 0.80},
    {"courseCode": "MAE4025", "jobIri": "Job_마케팅",    "weight": 0.60},

    # ── 국제한국학과 (Dept_GKS) ──────────────────────────────────────
    {"courseCode": "GKS2001", "jobIri": "Job_국제기구",  "weight": 0.65},
    {"courseCode": "GKS2001", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "GKS2002", "jobIri": "Job_데이터분석","weight": 0.65},
    {"courseCode": "GKS2002", "jobIri": "Job_국제기구",  "weight": 0.55},
    {"courseCode": "GKS2003", "jobIri": "Job_교육",      "weight": 0.75},
    {"courseCode": "GKS2003", "jobIri": "Job_국제기구",  "weight": 0.70},
    {"courseCode": "GKS3012", "jobIri": "Job_교육",      "weight": 0.70},
    {"courseCode": "GKS3012", "jobIri": "Job_국제기구",  "weight": 0.65},

    # ── AI공학과 (Dept_AIE) ──────────────────────────────────────────
    {"courseCode": "AIE3010", "jobIri": "Job_AI엔지니어","weight": 0.95},
    {"courseCode": "AIE3010", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "AIE4010", "jobIri": "Job_AI엔지니어","weight": 0.95},
    {"courseCode": "AIE4010", "jobIri": "Job_데이터분석","weight": 0.80},
    {"courseCode": "AIE4011", "jobIri": "Job_AI엔지니어","weight": 0.90},
    {"courseCode": "AIE4011", "jobIri": "Job_데이터분석","weight": 0.85},
    {"courseCode": "AIE4011", "jobIri": "Job_PM",        "weight": 0.65},
    {"courseCode": "AIE4014", "jobIri": "Job_AI엔지니어","weight": 0.95},
    {"courseCode": "AIE4014", "jobIri": "Job_소프트웨어","weight": 0.75},
    {"courseCode": "AIE3050", "jobIri": "Job_소프트웨어","weight": 0.90},
    {"courseCode": "AIE3050", "jobIri": "Job_AI엔지니어","weight": 0.75},
    {"courseCode": "AIE3051", "jobIri": "Job_소프트웨어","weight": 0.90},
    {"courseCode": "AIE3051", "jobIri": "Job_AI엔지니어","weight": 0.80},
    {"courseCode": "AIE3052", "jobIri": "Job_소프트웨어","weight": 0.85},
    {"courseCode": "AIE4050", "jobIri": "Job_소프트웨어","weight": 0.85},
    {"courseCode": "AIE4050", "jobIri": "Job_반도체",    "weight": 0.60},
    {"courseCode": "AIE4051", "jobIri": "Job_소프트웨어","weight": 0.80},
    {"courseCode": "AIE4051", "jobIri": "Job_반도체",    "weight": 0.65},
    {"courseCode": "AIE3053", "jobIri": "Job_반도체",    "weight": 0.75},
    {"courseCode": "AIE3053", "jobIri": "Job_소프트웨어","weight": 0.60},

    # ── 시스템반도체공학과 (Dept_SSE) ───────────────────────────────
    {"courseCode": "SSE3146", "jobIri": "Job_반도체",    "weight": 0.95},
    {"courseCode": "SSE3202", "jobIri": "Job_반도체",    "weight": 0.95},
    {"courseCode": "SSE4203", "jobIri": "Job_반도체",    "weight": 0.90},
    {"courseCode": "SSE4203", "jobIri": "Job_소프트웨어","weight": 0.70},
    {"courseCode": "SSE3141", "jobIri": "Job_반도체",    "weight": 0.80},
    {"courseCode": "SSE3141", "jobIri": "Job_AI엔지니어","weight": 0.65},
    {"courseCode": "SSE3131", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "SSE3132", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "SSE4183", "jobIri": "Job_반도체",    "weight": 0.85},
    {"courseCode": "SSE4183", "jobIri": "Job_소프트웨어","weight": 0.65},
    {"courseCode": "SSE4185", "jobIri": "Job_반도체",    "weight": 0.95},
    {"courseCode": "SSE4201", "jobIri": "Job_반도체",    "weight": 0.95},
    {"courseCode": "SSE4202", "jobIri": "Job_반도체",    "weight": 0.95},
    {'courseCode': 'TIS1002', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIS1002', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIS1005', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'TIS1005', 'jobIri': 'Job_금융', 'weight': 0.55},
    {'courseCode': 'TIC2001', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'TIC2001', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'TIC2001', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC2002', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'TIC2002', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'TIC2002', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'TIC2002', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIC3001', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC3001', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIC3001', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC3001', 'jobIri': 'Job_기획', 'weight': 0.6},
    {'courseCode': 'TIC2003', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'TIC2003', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC2003', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'TIC2003', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIC2004', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC2004', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIC2004', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'TIC2004', 'jobIri': 'Job_기획', 'weight': 0.6},
    {'courseCode': 'TIC2005', 'jobIri': 'Job_무역영업', 'weight': 0.9},
    {'courseCode': 'TIC2005', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIC2005', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC2005', 'jobIri': 'Job_금융', 'weight': 0.7},
    {'courseCode': 'TIC2006', 'jobIri': 'Job_회계세무', 'weight': 0.85},
    {'courseCode': 'TIC2006', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'TIC2006', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC2007', 'jobIri': 'Job_마케팅', 'weight': 0.85},
    {'courseCode': 'TIC2007', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC2007', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'TIC2008', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'TIC2008', 'jobIri': 'Job_회계세무', 'weight': 0.75},
    {'courseCode': 'TIC2008', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC3002', 'jobIri': 'Job_데이터분석', 'weight': 0.9},
    {'courseCode': 'TIC3002', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'TIC3002', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC3003', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIC3003', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC3003', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC3004', 'jobIri': 'Job_무역영업', 'weight': 0.9},
    {'courseCode': 'TIC3004', 'jobIri': 'Job_컨설팅', 'weight': 0.85},
    {'courseCode': 'TIC3004', 'jobIri': 'Job_기획', 'weight': 0.75},
    {'courseCode': 'TIC3004', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIC3005', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'TIC3005', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC3006', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'TIC3006', 'jobIri': 'Job_회계세무', 'weight': 0.75},
    {'courseCode': 'TIC3006', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC4001', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIC4001', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC4001', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIC4002', 'jobIri': 'Job_데이터분석', 'weight': 0.8},
    {'courseCode': 'TIC4002', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'TIC4002', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'TIC4003', 'jobIri': 'Job_무역영업', 'weight': 0.95},
    {'courseCode': 'TIC4003', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIC4003', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC4004', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'TIC4004', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC4004', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'TIC4005', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIC4005', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC4005', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC4006', 'jobIri': 'Job_무역영업', 'weight': 0.85},
    {'courseCode': 'TIC4006', 'jobIri': 'Job_PM', 'weight': 0.7},
    {'courseCode': 'TIC4006', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIC4007', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIC4007', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC4008', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIC4008', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC4008', 'jobIri': 'Job_컨설팅', 'weight': 0.6},
    {'courseCode': 'TIC4009', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIC4009', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIC4010', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'TIC4010', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIC4010', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIC4011', 'jobIri': 'Job_회계세무', 'weight': 0.95},
    {'courseCode': 'TIC4011', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'TIC4011', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC4012', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'TIC4012', 'jobIri': 'Job_컨설팅', 'weight': 0.6},
    {'courseCode': 'TIC4013', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'TIC4013', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC4014', 'jobIri': 'Job_무역영업', 'weight': 0.9},
    {'courseCode': 'TIC4014', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIC4014', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC4015', 'jobIri': 'Job_마케팅', 'weight': 0.9},
    {'courseCode': 'TIC4015', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC4015', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'TIC4016', 'jobIri': 'Job_컨설팅', 'weight': 0.9},
    {'courseCode': 'TIC4016', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC4016', 'jobIri': 'Job_기획', 'weight': 0.75},
    {'courseCode': 'TIC4017', 'jobIri': 'Job_무역영업', 'weight': 0.85},
    {'courseCode': 'TIC4017', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIC4017', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC4018', 'jobIri': 'Job_무역영업', 'weight': 0.85},
    {'courseCode': 'TIC4018', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIC4019', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC4019', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIC4019', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'TIC4020', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC4020', 'jobIri': 'Job_국제기구', 'weight': 0.75},
    {'courseCode': 'TIC4021', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC4021', 'jobIri': 'Job_국제기구', 'weight': 0.75},
    {'courseCode': 'TIC4022', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIC4022', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIC4023', 'jobIri': 'Job_무역영업', 'weight': 0.9},
    {'courseCode': 'TIC4023', 'jobIri': 'Job_국제기구', 'weight': 0.75},
    {'courseCode': 'TIC4023', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIC4024', 'jobIri': 'Job_무역영업', 'weight': 0.85},
    {'courseCode': 'TIC4024', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'TIC4024', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'TIC4025', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'TIC4025', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC4025', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIC4026', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'TIC4026', 'jobIri': 'Job_데이터분석', 'weight': 0.8},
    {'courseCode': 'TIC4026', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC4027', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIC4027', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'TIC4027', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIC4101', 'jobIri': 'Job_무역영업', 'weight': 0.95},
    {'courseCode': 'TIC4101', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'TIC4102', 'jobIri': 'Job_무역영업', 'weight': 0.9},
    {'courseCode': 'TIC4102', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIC4102', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'TIC4103', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'TIC4103', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIC4103', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIS1001', 'jobIri': 'Job_국제기구', 'weight': 0.75},
    {'courseCode': 'TIS1001', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'TIS1001', 'jobIri': 'Job_컨설팅', 'weight': 0.5},
    {'courseCode': 'TIR2001', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR2001', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'TIR2001', 'jobIri': 'Job_교육', 'weight': 0.65},
    {'courseCode': 'TIR2002', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR2002', 'jobIri': 'Job_PR언론', 'weight': 0.65},
    {'courseCode': 'TIR2002', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'TIR2003', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR2003', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIR2003', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIR2004', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR2004', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIR2005', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR2005', 'jobIri': 'Job_PR언론', 'weight': 0.6},
    {'courseCode': 'TIR2011', 'jobIri': 'Job_데이터분석', 'weight': 0.8},
    {'courseCode': 'TIR2011', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIR2011', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIR3001', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR3001', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIR3001', 'jobIri': 'Job_금융', 'weight': 0.65},
    {'courseCode': 'TIR3002', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR3002', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'TIR3003', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'TIR3003', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIR3003', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'TIR4001', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR4001', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'TIR4001', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIR2006', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR2006', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIR2007', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR2007', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIR2008', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR2008', 'jobIri': 'Job_PR언론', 'weight': 0.65},
    {'courseCode': 'TIR2009', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR2009', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'TIR2010', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIR2010', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'TIR2101', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'TIR2101', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'TIR3004', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR3004', 'jobIri': 'Job_PR언론', 'weight': 0.65},
    {'courseCode': 'TIR3005', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR3005', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'TIR3006', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'TIR3006', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'TIR3007', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR3007', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'TIR3007', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'TIR3008', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR3008', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'TIR3009', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'TIR3009', 'jobIri': 'Job_PR언론', 'weight': 0.65},
    {'courseCode': 'TIR4003', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIR4003', 'jobIri': 'Job_PR언론', 'weight': 0.6},
    {'courseCode': 'TIR4004', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIR4004', 'jobIri': 'Job_PR언론', 'weight': 0.65},
    {'courseCode': 'TIR4005', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIR4005', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'TIR4006', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIR4006', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'TIR4007', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'TIR4007', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'TIR4100', 'jobIri': 'Job_국제기구', 'weight': 0.75},
    {'courseCode': 'TIR4100', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'TIR4101', 'jobIri': 'Job_국제기구', 'weight': 0.75},
    {'courseCode': 'TIR4101', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'AAS2003', 'jobIri': 'Job_국제기구', 'weight': 0.85},
    {'courseCode': 'AAS2003', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'AAS2016', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'AAS2016', 'jobIri': 'Job_무역영업', 'weight': 0.7},
    {'courseCode': 'GIS1001', 'jobIri': 'Job_기획', 'weight': 0.5},
    {'courseCode': 'GIS1001', 'jobIri': 'Job_컨설팅', 'weight': 0.45},
    {'courseCode': 'GIS2001', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'GIS2001', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'GIS2001', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'GIS2002', 'jobIri': 'Job_회계세무', 'weight': 0.9},
    {'courseCode': 'GIS2002', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'GIS2002', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'GIS2003', 'jobIri': 'Job_마케팅', 'weight': 0.75},
    {'courseCode': 'GIS2003', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'GIS2003', 'jobIri': 'Job_기획', 'weight': 0.6},
    {'courseCode': 'GIS2004', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'GIS2004', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'GIS2004', 'jobIri': 'Job_소프트웨어', 'weight': 0.65},
    {'courseCode': 'GIS2005', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'GIS2005', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'GIS2005', 'jobIri': 'Job_무역영업', 'weight': 0.55},
    {'courseCode': 'GMT3001', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'GMT3001', 'jobIri': 'Job_회계세무', 'weight': 0.75},
    {'courseCode': 'GMT3001', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'GMT3002', 'jobIri': 'Job_마케팅', 'weight': 0.9},
    {'courseCode': 'GMT3002', 'jobIri': 'Job_기획', 'weight': 0.75},
    {'courseCode': 'GMT3002', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'GMT3003', 'jobIri': 'Job_인사', 'weight': 0.95},
    {'courseCode': 'GMT3003', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'GMT3003', 'jobIri': 'Job_컨설팅', 'weight': 0.6},
    {'courseCode': 'GMT3004', 'jobIri': 'Job_컨설팅', 'weight': 0.85},
    {'courseCode': 'GMT3004', 'jobIri': 'Job_기획', 'weight': 0.8},
    {'courseCode': 'GMT3004', 'jobIri': 'Job_PM', 'weight': 0.7},
    {'courseCode': 'GMT4001', 'jobIri': 'Job_무역영업', 'weight': 0.85},
    {'courseCode': 'GMT4001', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'GMT4001', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'GMT4002', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'GMT4002', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'GMT4002', 'jobIri': 'Job_기획', 'weight': 0.75},
    {'courseCode': 'GMT4002', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'GMT4003', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'GMT4003', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'GMT4003', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GMT4004', 'jobIri': 'Job_기획', 'weight': 0.8},
    {'courseCode': 'GMT4004', 'jobIri': 'Job_마케팅', 'weight': 0.75},
    {'courseCode': 'GMT4004', 'jobIri': 'Job_PM', 'weight': 0.7},
    {'courseCode': 'GMT4004', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'GMT4005', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'GMT4005', 'jobIri': 'Job_기획', 'weight': 0.8},
    {'courseCode': 'GMT4005', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'GMT4006', 'jobIri': 'Job_데이터분석', 'weight': 0.9},
    {'courseCode': 'GMT4006', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'GMT4006', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'GMT4006', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'GEC3001', 'jobIri': 'Job_컨설팅', 'weight': 0.85},
    {'courseCode': 'GEC3001', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'GEC3001', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'GEC3002', 'jobIri': 'Job_금융', 'weight': 0.9},
    {'courseCode': 'GEC3002', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'GEC3002', 'jobIri': 'Job_기획', 'weight': 0.6},
    {'courseCode': 'GEC4001', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'GEC4001', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'GEC4002', 'jobIri': 'Job_무역영업', 'weight': 0.95},
    {'courseCode': 'GEC4002', 'jobIri': 'Job_국제기구', 'weight': 0.8},
    {'courseCode': 'GEC4002', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'GEC4003', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'GEC4003', 'jobIri': 'Job_무역영업', 'weight': 0.8},
    {'courseCode': 'GEC4003', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'GEC4004', 'jobIri': 'Job_컨설팅', 'weight': 0.85},
    {'courseCode': 'GEC4004', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'GEC4004', 'jobIri': 'Job_금융', 'weight': 0.6},
    {'courseCode': 'GEC4005', 'jobIri': 'Job_데이터분석', 'weight': 0.95},
    {'courseCode': 'GEC4005', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'GEC4005', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'GEC4005', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'GEC4006', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'GEC4006', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'GEC4006', 'jobIri': 'Job_PR언론', 'weight': 0.6},
    {'courseCode': 'GEC4007', 'jobIri': 'Job_국제기구', 'weight': 0.9},
    {'courseCode': 'GEC4007', 'jobIri': 'Job_컨설팅', 'weight': 0.75},
    {'courseCode': 'GEC4007', 'jobIri': 'Job_무역영업', 'weight': 0.65},
    {'courseCode': 'GEC4008', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'GEC4008', 'jobIri': 'Job_금융', 'weight': 0.7},
    {'courseCode': 'GEC4008', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'GME3001', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.95},
    {'courseCode': 'GME3001', 'jobIri': 'Job_기획', 'weight': 0.85},
    {'courseCode': 'GME3001', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'GME3002', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.95},
    {'courseCode': 'GME3002', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'GME3002', 'jobIri': 'Job_마케팅', 'weight': 0.6},
    {'courseCode': 'GME3003', 'jobIri': 'Job_PR언론', 'weight': 0.95},
    {'courseCode': 'GME3003', 'jobIri': 'Job_마케팅', 'weight': 0.75},
    {'courseCode': 'GME3003', 'jobIri': 'Job_기획', 'weight': 0.6},
    {'courseCode': 'GME3000', 'jobIri': 'Job_PR언론', 'weight': 0.8},
    {'courseCode': 'GME3000', 'jobIri': 'Job_마케팅', 'weight': 0.7},
    {'courseCode': 'GME3000', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.65},
    {'courseCode': 'GME3004', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.85},
    {'courseCode': 'GME3004', 'jobIri': 'Job_PR언론', 'weight': 0.75},
    {'courseCode': 'GME3004', 'jobIri': 'Job_마케팅', 'weight': 0.7},
    {'courseCode': 'GME3004', 'jobIri': 'Job_국제기구', 'weight': 0.55},
    {'courseCode': 'GME3005', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GME3005', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'GME3005', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'GME4001', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.9},
    {'courseCode': 'GME4001', 'jobIri': 'Job_UX디자인', 'weight': 0.8},
    {'courseCode': 'GME4001', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'GME4002', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.95},
    {'courseCode': 'GME4002', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'GME4003', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.95},
    {'courseCode': 'GME4003', 'jobIri': 'Job_PM', 'weight': 0.55},
    {'courseCode': 'GME4004', 'jobIri': 'Job_UX디자인', 'weight': 0.95},
    {'courseCode': 'GME4004', 'jobIri': 'Job_PM', 'weight': 0.75},
    {'courseCode': 'GME4004', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'GME4005', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.95},
    {'courseCode': 'GME4005', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GME4006', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.9},
    {'courseCode': 'GME4006', 'jobIri': 'Job_UX디자인', 'weight': 0.8},
    {'courseCode': 'GME4006', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'GME4007', 'jobIri': 'Job_마케팅', 'weight': 0.95},
    {'courseCode': 'GME4007', 'jobIri': 'Job_PR언론', 'weight': 0.75},
    {'courseCode': 'GME4007', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'GME4008', 'jobIri': 'Job_PR언론', 'weight': 0.95},
    {'courseCode': 'GME4008', 'jobIri': 'Job_마케팅', 'weight': 0.7},
    {'courseCode': 'GME4009', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.85},
    {'courseCode': 'GME4009', 'jobIri': 'Job_PR언론', 'weight': 0.6},
    {'courseCode': 'GME4010', 'jobIri': 'Job_마케팅', 'weight': 0.9},
    {'courseCode': 'GME4010', 'jobIri': 'Job_UX디자인', 'weight': 0.75},
    {'courseCode': 'GME4010', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'KLC1002', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'GKE2001', 'jobIri': 'Job_교육', 'weight': 0.95},
    {'courseCode': 'GKE2001', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.6},
    {'courseCode': 'GKE2002', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE2002', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GKE2003', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE2003', 'jobIri': 'Job_국제기구', 'weight': 0.6},
    {'courseCode': 'GKE2004', 'jobIri': 'Job_교육', 'weight': 0.75},
    {'courseCode': 'GKE2004', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.7},
    {'courseCode': 'GKE2004', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GKE2005', 'jobIri': 'Job_교육', 'weight': 0.95},
    {'courseCode': 'GKE2005', 'jobIri': 'Job_국제기구', 'weight': 0.65},
    {'courseCode': 'GKE3001', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE3002', 'jobIri': 'Job_교육', 'weight': 0.8},
    {'courseCode': 'GKE3002', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GKE3003', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE3003', 'jobIri': 'Job_국제기구', 'weight': 0.6},
    {'courseCode': 'GKE3004', 'jobIri': 'Job_교육', 'weight': 0.75},
    {'courseCode': 'GKE3005', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE3005', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.7},
    {'courseCode': 'GKE3006', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE3006', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.65},
    {'courseCode': 'GKE3007', 'jobIri': 'Job_교육', 'weight': 0.95},
    {'courseCode': 'GKE3008', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE3009', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE3010', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE3011', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE3012', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE3013', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE3014', 'jobIri': 'Job_교육', 'weight': 0.9},
    {'courseCode': 'GKE3015', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.85},
    {'courseCode': 'GKE3015', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'GKE3015', 'jobIri': 'Job_마케팅', 'weight': 0.65},
    {'courseCode': 'GKE3016', 'jobIri': 'Job_교육', 'weight': 0.7},
    {'courseCode': 'GKE3016', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.65},
    {'courseCode': 'GKE3017', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GKE3017', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'GKE3018', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GKE3018', 'jobIri': 'Job_국제기구', 'weight': 0.7},
    {'courseCode': 'GKE3019', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.9},
    {'courseCode': 'GKE3019', 'jobIri': 'Job_PR언론', 'weight': 0.7},
    {'courseCode': 'GKE3020', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GKE3020', 'jobIri': 'Job_PR언론', 'weight': 0.75},
    {'courseCode': 'GKE3020', 'jobIri': 'Job_마케팅', 'weight': 0.65},
    {'courseCode': 'GKE3021', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GKE3022', 'jobIri': 'Job_무역영업', 'weight': 0.75},
    {'courseCode': 'GKE3022', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.7},
    {'courseCode': 'GKE3023', 'jobIri': 'Job_교육', 'weight': 0.85},
    {'courseCode': 'GKE3023', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'GKE3023', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.6},
    {'courseCode': 'GKE3024', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GKE3025', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.8},
    {'courseCode': 'GKE3026', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.85},
    {'courseCode': 'GKE3026', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GKE3027', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.9},
    {'courseCode': 'GKE3027', 'jobIri': 'Job_교육', 'weight': 0.7},
    {'courseCode': 'GKE3028', 'jobIri': 'Job_PM', 'weight': 0.8},
    {'courseCode': 'GKE3028', 'jobIri': 'Job_기획', 'weight': 0.75},
    {'courseCode': 'GKE3028', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'GKE3029', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'GKE3029', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.7},
    {'courseCode': 'GKE3029', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'GKE3030', 'jobIri': 'Job_콘텐츠제작', 'weight': 0.85},
    {'courseCode': 'GKE3030', 'jobIri': 'Job_마케팅', 'weight': 0.75},
    {'courseCode': 'GKE3030', 'jobIri': 'Job_PR언론', 'weight': 0.65},
    {'courseCode': 'STS2006', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'STS2006', 'jobIri': 'Job_AI엔지니어', 'weight': 0.55},
    {'courseCode': 'MAT1050', 'jobIri': 'Job_데이터분석', 'weight': 0.45},
    {'courseCode': 'MAT1060', 'jobIri': 'Job_데이터분석', 'weight': 0.45},
    {'courseCode': 'MAT2110', 'jobIri': 'Job_데이터분석', 'weight': 0.9},
    {'courseCode': 'MAT2110', 'jobIri': 'Job_AI엔지니어', 'weight': 0.85},
    {'courseCode': 'MAT2110', 'jobIri': 'Job_금융', 'weight': 0.7},
    {'courseCode': 'MAT2210', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT2210', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'MAT2210', 'jobIri': 'Job_교육', 'weight': 0.65},
    {'courseCode': 'MAT4110', 'jobIri': 'Job_연구', 'weight': 0.9},
    {'courseCode': 'MAT4110', 'jobIri': 'Job_교육', 'weight': 0.7},
    {'courseCode': 'MAT2010', 'jobIri': 'Job_연구', 'weight': 0.8},
    {'courseCode': 'MAT2010', 'jobIri': 'Job_교육', 'weight': 0.65},
    {'courseCode': 'MAT2120', 'jobIri': 'Job_연구', 'weight': 0.8},
    {'courseCode': 'MAT2120', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'MAT2230', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT2230', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'MAT4210', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT4210', 'jobIri': 'Job_금융', 'weight': 0.6},
    {'courseCode': 'MAT2220', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT2220', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'MAT4120', 'jobIri': 'Job_연구', 'weight': 0.9},
    {'courseCode': 'MAT4310', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT4310', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'MAT4320', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MATG210', 'jobIri': 'Job_연구', 'weight': 0.9},
    {'courseCode': 'MAT2410', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'MAT2410', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'MAT2420', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'MAT2510', 'jobIri': 'Job_AI엔지니어', 'weight': 0.75},
    {'courseCode': 'MAT2510', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'MAT3020', 'jobIri': 'Job_데이터분석', 'weight': 0.9},
    {'courseCode': 'MAT3020', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'MAT3020', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'MAT3110', 'jobIri': 'Job_AI엔지니어', 'weight': 0.85},
    {'courseCode': 'MAT3110', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'MAT3110', 'jobIri': 'Job_소프트웨어', 'weight': 0.65},
    {'courseCode': 'MAT3310', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT3310', 'jobIri': 'Job_교육', 'weight': 0.7},
    {'courseCode': 'MAT3410', 'jobIri': 'Job_데이터분석', 'weight': 0.9},
    {'courseCode': 'MAT3410', 'jobIri': 'Job_금융', 'weight': 0.8},
    {'courseCode': 'MAT3410', 'jobIri': 'Job_AI엔지니어', 'weight': 0.7},
    {'courseCode': 'MAT3420', 'jobIri': 'Job_금융', 'weight': 0.95},
    {'courseCode': 'MAT3420', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'MAT3420', 'jobIri': 'Job_컨설팅', 'weight': 0.6},
    {'courseCode': 'MAT3430', 'jobIri': 'Job_데이터분석', 'weight': 0.95},
    {'courseCode': 'MAT3430', 'jobIri': 'Job_금융', 'weight': 0.75},
    {'courseCode': 'MAT3430', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'MAT3440', 'jobIri': 'Job_AI엔지니어', 'weight': 0.85},
    {'courseCode': 'MAT3440', 'jobIri': 'Job_소프트웨어', 'weight': 0.7},
    {'courseCode': 'MAT3450', 'jobIri': 'Job_AI엔지니어', 'weight': 0.9},
    {'courseCode': 'MAT3450', 'jobIri': 'Job_소프트웨어', 'weight': 0.75},
    {'courseCode': 'MAT3450', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'MAT3451', 'jobIri': 'Job_기획', 'weight': 0.55},
    {'courseCode': 'MAT3460', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'MAT3460', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'MAT3470', 'jobIri': 'Job_데이터분석', 'weight': 0.95},
    {'courseCode': 'MAT3470', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'MAT3470', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'MAT4220', 'jobIri': 'Job_연구', 'weight': 0.8},
    {'courseCode': 'MAT4220', 'jobIri': 'Job_금융', 'weight': 0.6},
    {'courseCode': 'MAT4330', 'jobIri': 'Job_연구', 'weight': 0.8},
    {'courseCode': 'MAT4331', 'jobIri': 'Job_데이터분석', 'weight': 0.8},
    {'courseCode': 'MAT4331', 'jobIri': 'Job_AI엔지니어', 'weight': 0.75},
    {'courseCode': 'MAT4331', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'MAT4331', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'MAT4340', 'jobIri': 'Job_연구', 'weight': 0.85},
    {'courseCode': 'MAT4340', 'jobIri': 'Job_AI엔지니어', 'weight': 0.7},
    {'courseCode': 'MAT4510', 'jobIri': 'Job_연구', 'weight': 0.9},
    {'courseCode': 'MATG110', 'jobIri': 'Job_AI엔지니어', 'weight': 0.85},
    {'courseCode': 'MATG110', 'jobIri': 'Job_데이터분석', 'weight': 0.8},
    {'courseCode': 'MATQ981', 'jobIri': 'Job_교육', 'weight': 0.95},
    {'courseCode': 'MATQ982', 'jobIri': 'Job_교육', 'weight': 0.95},
    {'courseCode': 'MATQ983', 'jobIri': 'Job_교육', 'weight': 0.95},
    {'courseCode': 'CHM2101', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM2101', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHM2151', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM2151', 'jobIri': 'Job_PM', 'weight': 0.55},
    {'courseCode': 'CHM2102', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHM2102', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'CHM2152', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM2152', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHMG101', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHMG101', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'CHM2201', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHM2201', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'CHM2202', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHM2202', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'CHM2203', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM2203', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHM2231', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM2231', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'CHM2251', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM2252', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHMG201', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHMG201', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHMG202', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHMG202', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHM2301', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM2302', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM2303', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM2351', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'CHM2352', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'CHM2331', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM2332', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHMG301', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHMG302', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM2401', 'jobIri': 'Job_반도체', 'weight': 0.85},
    {'courseCode': 'CHM2402', 'jobIri': 'Job_반도체', 'weight': 0.85},
    {'courseCode': 'CHM2451', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHMG401', 'jobIri': 'Job_반도체', 'weight': 0.9},
    {'courseCode': 'CHMG402', 'jobIri': 'Job_반도체', 'weight': 0.9},
    {'courseCode': 'CHMG402', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'CHM2501', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHM2501', 'jobIri': 'Job_컨설팅', 'weight': 0.55},
    {'courseCode': 'CHM2601', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'CHM2601', 'jobIri': 'Job_AI엔지니어', 'weight': 0.55},
    {'courseCode': 'CHM2602', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'CHM2651', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'CHMG501', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHMG501', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'CHMG502', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'CHMG502', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'CHM4051', 'jobIri': 'Job_PM', 'weight': 0.8},
    {'courseCode': 'CHM4051', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM4052', 'jobIri': 'Job_PM', 'weight': 0.8},
    {'courseCode': 'CHM4052', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM4055', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'CHM4055', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'CHM4053', 'jobIri': 'Job_AI엔지니어', 'weight': 0.9},
    {'courseCode': 'CHM4053', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'CHM4053', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'CHM4054', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'CHM4054', 'jobIri': 'Job_PM', 'weight': 0.7},
    {'courseCode': 'CHM4056', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'CHM4056', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'CHM4057', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'CHM4057', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'CHM4203', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'CHM4203', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'CHM3100', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'CHM3100', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'CHMG601', 'jobIri': 'Job_교육', 'weight': 0.7},
    {'courseCode': 'CHMG601', 'jobIri': 'Job_PR언론', 'weight': 0.55},
    {'courseCode': 'BIO2121', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'BIO2121', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'BIO2122', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'BIO2122', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'BIO3123', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'BIO3123', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'BIO3124', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'BIO3124', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'BIO2131', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO2131', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'BIO2132', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO2132', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'BIO2111', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'BIO2111', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'BIO2141', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO2141', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'BIO2151', 'jobIri': 'Job_AI엔지니어', 'weight': 0.75},
    {'courseCode': 'BIO2151', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'BIO2601', 'jobIri': 'Job_AI엔지니어', 'weight': 0.75},
    {'courseCode': 'BIO2601', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO3161', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'BIO3161', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'BIO4441', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'BIO4441', 'jobIri': 'Job_데이터분석', 'weight': 0.75},
    {'courseCode': 'BIO4721', 'jobIri': 'Job_AI엔지니어', 'weight': 0.75},
    {'courseCode': 'BIO4721', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'BIOG153', 'jobIri': 'Job_AI엔지니어', 'weight': 0.85},
    {'courseCode': 'BIOG153', 'jobIri': 'Job_데이터분석', 'weight': 0.8},
    {'courseCode': 'BIO2311', 'jobIri': 'Job_반도체', 'weight': 0.6},
    {'courseCode': 'BIO2311', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'BIO4321', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO4321', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'BIO4331', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO4331', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'BIOG322', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIOG322', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'BIO2350', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'BIO2350', 'jobIri': 'Job_AI엔지니어', 'weight': 0.55},
    {'courseCode': 'BIO2511', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'BIO2511', 'jobIri': 'Job_컨설팅', 'weight': 0.6},
    {'courseCode': 'BIO3711', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO3711', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'BIO3712', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO4351', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'BIO4351', 'jobIri': 'Job_AI엔지니어', 'weight': 0.7},
    {'courseCode': 'BIO4252', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'BIO4252', 'jobIri': 'Job_AI엔지니어', 'weight': 0.7},
    {'courseCode': 'BIO4251', 'jobIri': 'Job_데이터분석', 'weight': 0.95},
    {'courseCode': 'BIO4251', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'BIOG241', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'BIOG241', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIOG241', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'BIOG232', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'BIOG232', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO2522', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'BIO3311', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'BIO4521', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'BIO4911', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO4911', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'BIOG511', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'BIO2701', 'jobIri': 'Job_컨설팅', 'weight': 0.6},
    {'courseCode': 'BIO2701', 'jobIri': 'Job_기획', 'weight': 0.55},
    {'courseCode': 'BIO3212', 'jobIri': 'Job_기획', 'weight': 0.75},
    {'courseCode': 'BIO3212', 'jobIri': 'Job_컨설팅', 'weight': 0.65},
    {'courseCode': 'BIOG001', 'jobIri': 'Job_기획', 'weight': 0.85},
    {'courseCode': 'BIOG001', 'jobIri': 'Job_컨설팅', 'weight': 0.8},
    {'courseCode': 'BIOG001', 'jobIri': 'Job_PM', 'weight': 0.75},
    {'courseCode': 'BIO4100', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'BIO4100', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'BIO4921', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'BIO4921', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'BIO4931', 'jobIri': 'Job_PM', 'weight': 0.8},
    {'courseCode': 'BIO4931', 'jobIri': 'Job_반도체', 'weight': 0.6},
    {'courseCode': 'BIO4203', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'BIO4203', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'BIO3100', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'BIO3100', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'PHY2001', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY2001', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'PHY2003', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'PHY2003', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'PHY2004', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'PHY2004', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'PHY2005', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHY2005', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'PHY2009', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHY2009', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHY2101', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY2101', 'jobIri': 'Job_PM', 'weight': 0.55},
    {'courseCode': 'PHY2102', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY2102', 'jobIri': 'Job_PM', 'weight': 0.55},
    {'courseCode': 'PHY3001', 'jobIri': 'Job_반도체', 'weight': 0.85},
    {'courseCode': 'PHY3001', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'PHY3002', 'jobIri': 'Job_반도체', 'weight': 0.85},
    {'courseCode': 'PHY3002', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'PHY3003', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHY3003', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHY3004', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHY3004', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHY3004', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'PHY3101', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY3101', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'PHY3102', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY3102', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'PHY2002', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'PHY2006', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHY2006', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'PHY2007', 'jobIri': 'Job_반도체', 'weight': 0.9},
    {'courseCode': 'PHY2007', 'jobIri': 'Job_소프트웨어', 'weight': 0.6},
    {'courseCode': 'PHY2008', 'jobIri': 'Job_반도체', 'weight': 0.9},
    {'courseCode': 'PHY2008', 'jobIri': 'Job_소프트웨어', 'weight': 0.6},
    {'courseCode': 'PHY4001', 'jobIri': 'Job_반도체', 'weight': 0.95},
    {'courseCode': 'PHY4001', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'PHY4002', 'jobIri': 'Job_반도체', 'weight': 0.95},
    {'courseCode': 'PHY4002', 'jobIri': 'Job_PM', 'weight': 0.6},
    {'courseCode': 'PHY4009', 'jobIri': 'Job_반도체', 'weight': 1.0},
    {'courseCode': 'PHY4009', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'PHY4003', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'PHY4003', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHY4004', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'PHY4005', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHY4005', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'PHY4006', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHY4006', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'PHY4007', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'PHY4007', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'PHY4007', 'jobIri': 'Job_소프트웨어', 'weight': 0.75},
    {'courseCode': 'PHY4008', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'PHY4008', 'jobIri': 'Job_AI엔지니어', 'weight': 0.8},
    {'courseCode': 'PHY4008', 'jobIri': 'Job_소프트웨어', 'weight': 0.75},
    {'courseCode': 'PHY4010', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'PHY4011', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHY4012', 'jobIri': 'Job_반도체', 'weight': 0.9},
    {'courseCode': 'PHY4012', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'PHY4013', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHY4013', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'PHY4015', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHY4015', 'jobIri': 'Job_AI엔지니어', 'weight': 0.6},
    {'courseCode': 'PHY4016', 'jobIri': 'Job_반도체', 'weight': 0.9},
    {'courseCode': 'PHY4016', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'PHY4017', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHY4019', 'jobIri': 'Job_반도체', 'weight': 0.8},
    {'courseCode': 'PHY4019', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHY4101', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHY4101', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'PHY4202', 'jobIri': 'Job_교육', 'weight': 0.7},
    {'courseCode': 'PHY4202', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'PHY4203', 'jobIri': 'Job_컨설팅', 'weight': 0.7},
    {'courseCode': 'PHY4203', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'PHYG001', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHYG001', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'PHYG003', 'jobIri': 'Job_반도체', 'weight': 0.75},
    {'courseCode': 'PHYG003', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHYG003', 'jobIri': 'Job_AI엔지니어', 'weight': 0.65},
    {'courseCode': 'PHYG006', 'jobIri': 'Job_데이터분석', 'weight': 0.65},
    {'courseCode': 'PHYG006', 'jobIri': 'Job_AI엔지니어', 'weight': 0.7},
    {'courseCode': 'PHYG004', 'jobIri': 'Job_AI엔지니어', 'weight': 0.95},
    {'courseCode': 'PHYG004', 'jobIri': 'Job_데이터분석', 'weight': 0.9},
    {'courseCode': 'PHYG004', 'jobIri': 'Job_소프트웨어', 'weight': 0.75},
    {'courseCode': 'PHYG005', 'jobIri': 'Job_AI엔지니어', 'weight': 0.95},
    {'courseCode': 'PHYG005', 'jobIri': 'Job_데이터분석', 'weight': 0.85},
    {'courseCode': 'PHYG005', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY3501', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'PHY3501', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY3502', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'PHY3502', 'jobIri': 'Job_반도체', 'weight': 0.7},
    {'courseCode': 'PHY4201', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'PHY4201', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'PHY4204', 'jobIri': 'Job_PM', 'weight': 0.85},
    {'courseCode': 'PHY4204', 'jobIri': 'Job_반도체', 'weight': 0.65},
    {'courseCode': 'PHY3510', 'jobIri': 'Job_기획', 'weight': 0.7},
    {'courseCode': 'PHY3510', 'jobIri': 'Job_PM', 'weight': 0.65},
    {'courseCode': 'PHY3515', 'jobIri': 'Job_기획', 'weight': 0.65},
    {'courseCode': 'PHY3515', 'jobIri': 'Job_교육', 'weight': 0.6},
    {'courseCode': 'SCI1011', 'jobIri': 'Job_데이터분석', 'weight': 0.6},
    {'courseCode': 'SCI1011', 'jobIri': 'Job_AI엔지니어', 'weight': 0.55},
    {'courseCode': 'SCI1012', 'jobIri': 'Job_반도체', 'weight': 0.6},
    {'courseCode': 'SCI1012', 'jobIri': 'Job_데이터분석', 'weight': 0.5},
    {'courseCode': 'SCI1013', 'jobIri': 'Job_반도체', 'weight': 0.6},
    {'courseCode': 'SCI1014', 'jobIri': 'Job_데이터분석', 'weight': 0.55},
    {'courseCode': 'SCI1014', 'jobIri': 'Job_AI엔지니어', 'weight': 0.5},
    {'courseCode': 'SCI1021', 'jobIri': 'Job_AI엔지니어', 'weight': 0.75},
    {'courseCode': 'SCI1021', 'jobIri': 'Job_데이터분석', 'weight': 0.7},
    {'courseCode': 'SCI1021', 'jobIri': 'Job_소프트웨어', 'weight': 0.6},
]

# ── 전공-직무 연결 (TARGETS_JOB_ROLE) ────────────────────────────
# 해당 전공이 타겟으로 하는 주요 직무 (상위 3~5개)
MAJOR_JOB_TARGETS: list[dict] = [
    {"majorIri": "Major_CHI_단일",   "jobIri": "Job_무역영업"},
    {"majorIri": "Major_CHI_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_CHI_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_MGT_단일",   "jobIri": "Job_컨설팅"},
    {"majorIri": "Major_MGT_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_MGT_단일",   "jobIri": "Job_기획"},
    {"majorIri": "Major_MGT_단일",   "jobIri": "Job_금융"},
    {"majorIri": "Major_MGT_단일",   "jobIri": "Job_인사"},
    {"majorIri": "Major_ECO_단일",   "jobIri": "Job_금융"},
    {"majorIri": "Major_ECO_단일",   "jobIri": "Job_컨설팅"},
    {"majorIri": "Major_ECO_단일",   "jobIri": "Job_데이터분석"},
    {"majorIri": "Major_CSE_단일",   "jobIri": "Job_소프트웨어"},
    {"majorIri": "Major_CSE_단일",   "jobIri": "Job_AI엔지니어"},
    {"majorIri": "Major_CSE_단일",   "jobIri": "Job_PM"},
    {"majorIri": "Major_EEE_단일",   "jobIri": "Job_반도체"},
    {"majorIri": "Major_EEE_단일",   "jobIri": "Job_AI엔지니어"},
    {"majorIri": "Major_EEE_단일",   "jobIri": "Job_소프트웨어"},
    {"majorIri": "Major_KOR_단일",   "jobIri": "Job_교육"},
    {"majorIri": "Major_KOR_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_KOR_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_ENG_단일",   "jobIri": "Job_교육"},
    {"majorIri": "Major_ENG_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_ENG_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_EUR_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_EUR_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_EUR_단일",   "jobIri": "Job_교육"},
    {"majorIri": "Major_AMC_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_AMC_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_AMC_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_HIS_단일",   "jobIri": "Job_교육"},
    {"majorIri": "Major_HIS_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_PHI_단일",   "jobIri": "Job_교육"},
    {"majorIri": "Major_PHI_단일",   "jobIri": "Job_컨설팅"},
    {"majorIri": "Major_SOC_단일",   "jobIri": "Job_컨설팅"},
    {"majorIri": "Major_SOC_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_SOC_단일",   "jobIri": "Job_인사"},
    {"majorIri": "Major_POL_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_POL_단일",   "jobIri": "Job_컨설팅"},
    {"majorIri": "Major_POL_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_PSY_단일",   "jobIri": "Job_인사"},
    {"majorIri": "Major_PSY_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_PSY_단일",   "jobIri": "Job_PM"},
    {"majorIri": "Major_MAT_단일",   "jobIri": "Job_데이터분석"},
    {"majorIri": "Major_MAT_단일",   "jobIri": "Job_금융"},
    {"majorIri": "Major_MAT_단일",   "jobIri": "Job_AI엔지니어"},
    {"majorIri": "Major_BIO_단일",   "jobIri": "Job_데이터분석"},
    {"majorIri": "Major_BIO_단일",   "jobIri": "Job_기획"},
    {"majorIri": "Major_JAS_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_JAS_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_JAS_단일",   "jobIri": "Job_기획"},
    {"majorIri": "Major_MAE_단일",   "jobIri": "Job_PR언론"},
    {"majorIri": "Major_MAE_단일",   "jobIri": "Job_기획"},
    {"majorIri": "Major_MAE_단일",   "jobIri": "Job_마케팅"},
    {"majorIri": "Major_GKS_단일",   "jobIri": "Job_국제기구"},
    {"majorIri": "Major_GKS_단일",   "jobIri": "Job_교육"},
    {"majorIri": "Major_AIE_단일",   "jobIri": "Job_AI엔지니어"},
    {"majorIri": "Major_AIE_단일",   "jobIri": "Job_데이터분석"},
    {"majorIri": "Major_AIE_단일",   "jobIri": "Job_소프트웨어"},
    {"majorIri": "Major_SSE_단일",   "jobIri": "Job_반도체"},
    {"majorIri": "Major_SSE_단일",   "jobIri": "Job_소프트웨어"},
]
